### ISSUE TITLE
Store owners can create profile easily

### ISSUE THREAD

**Issue by cnasenberg** [smallbusinesshero/business#3]
As a store owner, I who would like to easily join Small Business Hero. 

Acceptance Criteria  
- I know what information to provide. 
- I know where to provide it. 
- I know that I can send an email to partner@smallbusinesshero.de if I have any other questions. 
- I understand that it might take a little while until I get a response. 

Subtasks 
- [x] Come up with UX, store owners should understand exactly how to join (also see https://github.com/smallbusinesshero/ux-ui/issues/3) 
- [ ] This probably needs some text, please talk to @annaebrashear! 
- [ ] Adapt frontend.

**Comment by KonstiSchaetz** [comment]
> This is a very quick fix, before we have the form ready.
> 
> As a store owner, I who would like to understand exactly how I can join Small Business Hero.
> 
> Acceptance Criteria
> 
> * I know that I can write an email to [partner@smallbusinesshero.de](mailto:partner@smallbusinesshero.de) and I know what information to provide.

we need the following information from Shop Owners:
- Name des Ladens* 
- Adresse und PLZ des Ladens* 
- Stadtteil und Kiez/Viertel* 
- Inhaber/in* 
- Kurze Beschreibung des Shops* 
- Produktkategorie* (list exists in [issue: "product development"](https://github.com/smallbusinesshero/business/issues/5))
- Telefon*
- website URL
- E-Mail
- Instagram
- Facebook
- Foto oder Logo des Shops hochladen* 
*Pflichtfeld 

> * I know that I can send an email to [partner@smallbusinesshero.de](mailto:partner@smallbusinesshero.de) if I have any other questions. 

> * I understand that it might take a little while until I get a response.
> 
> Subtasks
> 
> * [ ]  Come up with UX, store owners should understand exactly how to join (also see [smallbusinesshero/ux-ui#3](https://github.com/smallbusinesshero/ux-ui/issues/3))
> * [ ]  This probably needs some text, please talk to @annaebrashear!
> * [ ]  Frontend implementation.

**Comment by jesshurf** [comment]
Link to google form is here: https://forms.gle/KXbWLSXZXLgqi6yt5

Link to folder for photo uploads is here: https://drive.google.com/drive/folders/0B8kQPv7PZ4yIflMwTUNOWmJUbFdjUWl2QWx2cHQwVEQwamJ3bEVtNVZfa1BOTEdmUnB3NkU?usp=sharing

**Comment by jonathan-wiens** [comment]
I'd like to suggest an introductory text to the form as a small on boarding for the store owner, so that they understand the process their getting into.

I've also removed the section for video and photo that forced the store owners to sign in with a Google address (I backed it up, just in case we need it again), as discussed in our Monday check-in

Can somebody check it? @cnasenberg @KonstiSchaetz @andreas

--

Du willst Deinen Laden völlig kostenlos und ohne Haken anmelden? Du willst Deine Reichweite erweitern, neue Kunden erreichen und Deinem einmaligen Laden eine Onlinepräsenz verschaffen, die sie verdient?

Hier bist Du richtig!

Fülle einfach das folgende Formular nach besten Wissen und Gewissen aus. Unser Team 

> nach besteM Wissen und Gewissen...

meldet sich bei Dir und wird Dich nach weiteren Infos, wie zum Beispiel um ein Profilfoto und Produktinfos, die Du über Deinen Laden vertreibst, bitten.

Zum Abschluss fügen wir Deinen besonderen Laden der Small Business Hero Plattform hinzu und es kann los gehen!

Schreibe email_address falls Du in der Zwischenzeit Fragen hast!

--

If everyone's fine with this / wants to change it we can add it to the form asap?

**Comment by hellandreas** [comment]
@jonathan-wiens Sounds good!

**Comment by jonathan-wiens** [comment]
Thanks, will put it into the form

**Comment by jonathan-wiens** [comment]
Done: https://forms.gle/QjTuquDNCgXxYt429

**Comment by KonstiSchaetz** [comment]
Ja passt gut!

**Comment by cnasenberg** [comment]
We do have the Google Forms registration form, so I guess we are done. :) I will close this issue, just re-open it if you feel that there's something else to do.
